services:
  opencloning:
    build: .
    image: manulera/opencloning:local
    ports:
      - "8000:8000"

    environment:
    #  BACKEND IMAGE ENVIRONMENT VARIABLES
    #  ===================================
    #
    #  This value limits the maximum sequence length that can be requested from the NCBI
    #  via genome coordinates or sequenece accession (Repository > Genbank). This is to prevent
    #  loading of entire genomes, which would take a long time and not render properly in the
    #  frontend. The default value is 500000 base pairs.
    #
    #  NCBI_MAX_SEQUENCE_LENGTH=500000
    #
    #
    #   If you want to allow other origins via CORS (comma separated)
    #   IMPORTANT: Do not add a trailing slash to the URLs:
    #     > Do not use http://localhost:3000/, but http://localhost:3000
    #   default value: unset (http://localhost:3000 and http://localhost:5173 allowed)
      # - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    #
    #   If you want to use a subpath of the domain, set ROOT_PATH,
    #   this is the equivalent of --root-path in uvicorn, so the routes
    #   without this prefix will also work (e.g. / will be the same as /opencloning/).
    #   IMPORTANT: Do not add trailing slash, and don't use quotes.
    #   default value: ""
      # - ROOT_PATH=/opencloning
    #
    #
    #   Set this if you want to use plannotate
    #   default value: unset
      - PLANNOTATE_URL=http://plannotate:8000

    # Set this if you want to use a proxy for the external requests made by the backend
    # (example is using mitmproxy locally on port 8080)
    # default value: unset
      # - PROXY_URL=http://host.docker.internal:8080
    # Set this if you want to use a cert file for the proxy (e.g. when testing locally using mitmproxy and USE_HTTPS=true)
    # This file should be mounted. The path is absolute to the container.
    # default value: unset
      # - PROXY_CERT_FILE=/certs/proxy.pem

    # Set to true if you are using HTTPS, you will have to provide cert files (see volumes section)
    # default value: false
      # - USE_HTTPS=true
    #
    # Set if you want to restrict the access to external services (by default, all are allowed)
    # comma separated list of URLs
    # default value: unset (all are allowed)
    # For a full list, see https://github.com/manulera/OpenCloning_backend/blob/master/src/opencloning/app_settings.py
      # - ALLOWED_EXTERNAL_URLS=https://www.addgene.org/,https://media.addgene.org/,https://seva-plasmids.com/,https://api.ncbi.nlm.nih.gov/datasets/v2alpha/,https://eutils.ncbi.nlm.nih.gov/entrez/eutils/,https://www.snapgene.com/local/fetch.php,https://benchling.com/,https://assets.opencloning.org/annotated-igem-distribution,http://www.euroscarf.de/,https://wekwikgene.wllsb.edu.cn




    # FRONTEND IMAGE ENVIRONMENT VARIABLES
    # ===================================
    #
    #   Set this if you are not using "/" as rooth path. Note the trailing slash.
    #   default: "/"
      # - BACKEND_URL=/opencloning/
    # Set to true if you want to enable the annotation tool (plannotate), false otherwise
    # default value: false
      # - ENABLE_PLANNOTATE=true
    # Set to true if you want to enable the assembler tool (experimental for now), false otherwise
    # default value: false
      # - ENABLE_ASSEMBLER=true
    # Set to false to hide the app bar
    # default value: true
      # - SHOW_APP_BAR=false
    # Set to the appropriate value
    # default value: ""
      # - DATABASE=elabftw
    # Set to true if you want to disable external requests (e.g. to AddGene, NCBI, etc.)
    # default value: false
      # - NO_EXTERNAL_REQUESTS=true
    #
    # Include the path of a folder to be mounted in the public folder of the frontend.
    # and that contains sequences and syntaxes that can be loaded from the frontend.
    # It MUST be a subfolder within assets/, since that's where the backend serves
    # static content from.
    # default value: unset
      - STATIC_CONTENT_PATH=assets/static_content

    volumes:
      # Cert folder
      # If USE_HTTPS=true, must contain certificate and key files named cert.pem and key.pem
      # If you set PROXY_CERT_FILE, you can mount that file here
      # - type: bind
      #   source: ./certs
      #   target: /certs
      #   read_only: true
      # If STATIC_CONTENT_PATH is set, it will be mounted in the public folder of the frontend.
      # and that contains sequences and syntaxes that can be loaded from the frontend.
      - type: bind
        source: ./static_content
        target: /home/backend/frontend/assets/static_content
        read_only: true



  plannotate:
    image: manulera/plannotate-api
