version: "3.9"

services:
  opencloningbackend:
    image: manulera/opencloningbackend:prod
    environment:
      - ALLOWED_ORIGINS=https://localhost:3000
    ports:
      - "8000:8000"

  opencloningfrontend:
    image: manulera/opencloningfrontend:local
    ports:
      - "3000:3000"

  # plannotate:
  #   restart: always
  #   image: manulera/plannotate-api
