version: "3.9"

services:
  opencloningbackend:
    image: manulera/opencloningbackend:prod
    environment:
      - ALLOWED_ORIGINS=https://localhost:3000
    ports:
      - "8000:8000"

  opencloningfrontend:
    image: manulera/opencloningfrontend:prod
    ports:
      - "3000:3000"
    # environment:
      # - ENABLE_PLANNOTATE=true
      # - ENABLE_ASSEMBLER=true

  # plannotate:
  #   restart: always
  #   image: manulera/plannotate-api
